"use client";

import { useRef, useState } from "react";
import { UploadSimple } from "@phosphor-icons/react";
import { api, type Detection } from "@/lib/api";
import { fmt } from "@/lib/format";
import { Button, Label, Textarea, Help, FieldError, Panel, Notice, Skeleton, Metric } from "@/components/ui";
import { VerdictBadge, ZMeter } from "@/components/verdict";
import { useHealth } from "@/components/status";

export default function DetectPage() {
  const { health } = useHealth();
  const [text, setText] = useState("");
  const [loaded, setLoaded] = useState<{ name: string; text: string; sidecar?: Record<string, unknown> } | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<Detection | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  async function onFiles(files: FileList | null) {
    if (!files?.length) return;
    setError(null);
    let txt: File | null = null;
    let side: File | null = null;
    for (const f of Array.from(files)) {
      if (f.name.endsWith(".json")) side = f;
      else txt = f;
    }
    if (!txt) return setError("Choose a .txt file (a matching .json sidecar may be added alongside).");
    try {
      const content = (await txt.text()).replace(/^﻿/, "");
      let sidecar: Record<string, unknown> | undefined;
      if (side) {
        try {
          sidecar = JSON.parse(await side.text());
        } catch {
          sidecar = undefined;
        }
      }
      setText(content);
      setLoaded({ name: txt.name, text: content.trim(), sidecar });
      setResult(null);
    } catch {
      setError(`Could not read ${txt.name} as UTF-8 text.`);
    }
  }

  async function analyze() {
    setError(null);
    const t = text.trim();
    if (!t) return setError("Paste or open text to analyze.");
    setBusy(true);
    setResult(null);
    const unchanged = loaded && t === loaded.text;
    const extra = unchanged && loaded?.sidecar
      ? {
          mode: loaded.sidecar.mode ?? "",
          seed: loaded.sidecar.seed ?? "",
          max_new_tokens: loaded.sidecar.max_new_tokens ?? "",
          gen_tokens: loaded.sidecar.new_tokens ?? "",
        }
      : {};
    try {
      setResult(
        await api.detect({
          text: t,
          filename: unchanged ? loaded!.name : "",
          source: unchanged ? "file" : "manual",
          extra,
        }),
      );
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  function clear() {
    setText("");
    setLoaded(null);
    setResult(null);
    setError(null);
    if (fileRef.current) fileRef.current.value = "";
  }

  const th = { detection: 4, possible: 2 };

  return (
    <div className="grid gap-8 lg:grid-cols-[minmax(0,7fr)_minmax(0,5fr)]">
      <section>
        <h1 className="text-2xl font-semibold tracking-tight">Detect</h1>
        <p className="mt-1 text-sm text-fg-muted">
          Re-score a text against this installation&apos;s key. Every analysis is logged with its run id.
        </p>
        <div className="mt-6 space-y-5">
          <div className="space-y-2">
            <Label htmlFor="file">Open a .txt (optionally with its .json sidecar)</Label>
            <input
              ref={fileRef}
              id="file"
              type="file"
              accept=".txt,.json"
              multiple
              onChange={(e) => onFiles(e.target.files)}
              className="block w-full text-sm text-fg-muted file:mr-3 file:rounded-full file:border file:border-line-strong file:bg-bg-elev file:px-3 file:py-1.5 file:text-sm file:text-fg"
            />
            {loaded && (
              <Help>
                <UploadSimple size={12} className="mr-1 inline" />
                {loaded.name}
                {loaded.sidecar ? ` (${String(loaded.sidecar.mode)} mode, seed ${String(loaded.sidecar.seed)})` : ""}
              </Help>
            )}
          </div>
          <div className="space-y-2">
            <Label htmlFor="text">Text to analyze</Label>
            <Textarea id="text" rows={14} value={text} onChange={(e) => setText(e.target.value)} />
            <Help>Only text generated by MarkText with this key can be recognised. Edited text is logged as manual input.</Help>
          </div>
          <FieldError>{error}</FieldError>
          <div className="flex gap-2">
            <Button size="lg" onClick={analyze} disabled={busy}>
              {busy ? "Analyzing" : "Analyze"}
            </Button>
            <Button variant="ghost" size="lg" onClick={clear}>
              Clear
            </Button>
          </div>
        </div>
      </section>

      <section aria-live="polite">
        <h2 className="text-sm font-medium text-fg-muted">Detection results</h2>
        <Panel className="mt-3 p-5">
          {busy && (
            <div className="space-y-3">
              <Skeleton className="h-8 w-1/2" />
              <Skeleton className="h-3 w-full" />
              <div className="grid grid-cols-2 gap-4 pt-2">
                <Skeleton className="h-12" />
                <Skeleton className="h-12" />
                <Skeleton className="h-12" />
                <Skeleton className="h-12" />
              </div>
            </div>
          )}
          {!busy && !result && <p className="py-8 text-center text-sm text-fg-muted">No analysis yet.</p>}
          {result && !busy && (
            <div className="space-y-5">
              <div className="flex items-center justify-between gap-3">
                <VerdictBadge label={result.label} className="text-sm" />
                <span className="tabular font-mono text-xs text-fg-faint">run {result.run_id ?? "not logged"}</span>
              </div>
              <ZMeter z={result.z_score} detection={th.detection} possible={th.possible} />
              <div className="grid grid-cols-2 gap-x-4 gap-y-5">
                <Metric label="Tokens analyzed" value={fmt.int(result.num_tokens_scored)} />
                <Metric label="Green tokens" value={fmt.int(result.num_green_tokens)} />
                <Metric label="Green share" value={fmt.pct(result.green_fraction, 1)} hint="chance level is 50%" />
                <Metric label="p-value" value={fmt.p(result.p_value)} />
              </div>
              {result.log_error && <Notice tone="danger">Result shown but not logged: {result.log_error}</Notice>}
            </div>
          )}
        </Panel>
        <p className="mt-3 text-xs text-fg-muted">
          MarkText detects only text it generated with its own key and parameters. It is not a universal AI-text detector;
          NOT DETECTED means this watermark was not found, not that a person wrote the text.
          {health?.key_is_public ? " This installation still uses the public default key." : ""}
        </p>
      </section>
    </div>
  );
}
